version: "3.9"

services:
  sample-api:
    build:
      context: ./sample-api
      dockerfile: Dockerfile
    container_name: sample-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=false

    # sample-api dependency preprocessing-service
    depends_on:
      preprocessing-service:
        condition: service_healthy

    # HEALTHCHECK (Mandatory)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

    # RESTART POLICY (Optional)
    restart: unless-stopped

    # RESOURCE LIMITS (Optional
    #I would not keep this active on this file because even with a small VM SKU for example, this will not be a big consumption)

    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: "512M"

    # LOGGING CONFIGURATION (Optional)
    logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"

  preprocessing-service:
    build:
      context: ./preprocessing-service
      dockerfile: Dockerfile
    container_name: preprocessing-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DEBUG=false

    # HEALTHCHECK (Mandatory)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

    # RESTART POLICY (Optional)
    restart: unless-stopped
    
    #RESOURCE LIMITS (Optional
    #I would not keep this active on this file because even with a small VM SKU for example, this will not be a big consumption)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.50"
    #       memory: "512M"

    # LOGGING CONFIGURATION (Optional)
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  # MONITORING STACK (Optional)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus-data:/prometheus
  #   depends_on:
  #     sample-api:
  #       condition: service_healthy
  #     preprocessing-service:
  #       condition: service_healthy

  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     ports:
       - "3000:3000"
     volumes:
       - grafana-data:/var/lib/grafana
     depends_on:
       - prometheus

# CUSTOM NETWORK (Mandatory)
networks: 
  default:
    name: devops-challenge-network
