namespace: devops-challenge

resources:
  - ../base

images:
  - name: sample-api
    newName: sample-api
    newTag: production
  - name: preprocessing-service
    newName: preprocessing-service
    newTag: production