apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-challenge
data:
  APP_ENV: "staging"
  DEBUG: "false"
  SAMPLE_API_PORT: "5000"
  PREPROCESS_PORT: "5001"
  PREPROCESS_URL: "http://preprocessing-service:5001/preprocess"