apiVersion: v1
kind: Service
metadata:
  name: sample-api
  namespace: devops-challenge
spec:
  selector:
    app: sample-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP